#! /bin/bash


# Autostart

compton --config ~/.config/compton.conf -b &
wal -i Pictures/wallpaper/nightlife-momentum-hc-3840x2160.jpg
#feh -z --bg-fill ~/pics/wallpapers/solid &
$HOME/.config/polybar/launch.sh &
setxkbmap -model pc105 -layout us,es -option grp:alt_shift_toggle &
systemctl --user --now start greenclip.service &
sxhkd &
#xautolock -time 10 -locker "~/scripts/lock.sh" &
xsetroot -cursor_name left_ptr &


# Workspaces

# bspc monitor -d web code media edit graphics other
bspc monitor -d I II III IV V VI VII VIII IX

# Source the colors

source "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"


# Use the line below if you are on bspwm >= 0.9.4

bspc config presel_feedback_color "$color1"


# Borders and Gaps

bspc config border_width         1.5
bspc config window_gap          7

bspc config bottom_padding 0
bspc config top_padding 40 

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config click_to_focus       true


# Rules
d
bspc rule -a Xarchiver state=floating
bspc rule -a Leafpad state=floating
bspc rule -a Pcmanfm state=floating focus=on
bspc rule -a URxvt state=floating
bspc rule -a feh state=floating


# Restart dunst with the new color scheme

mkdir -p  "${HOME}/.config/dunst"
ln -sf    "${HOME}/.cache/wal/bspwm-dunstrc" "${HOME}/.config/dunst/bspwm-dunstrc"

pkill dunst
dunst -conf ~/.config/dunst/bspwm-dunstrc &

